### ISSUE TITLE
Searching in repository

### ISSUE THREAD

**Issue by Rud5G** [thommay/chef-rewind#1]
Because this is a forked instance
![image](https://cloud.githubusercontent.com/assets/27158/6541922/9b4e8d86-c4e8-11e4-8289-9a505f613ca2.png)

**Comment by meddle0x53** [comment]
+1

**Comment by lamont-granquist** [comment]
@thommay should close this as well, its deprecated so never fixing it.

should probably shut off issues as well in settings
