### ISSUE TITLE
Allow usage in Resource class

### ISSUE THREAD

**Issue by ceilfors** [thommay/chef-rewind#6]
As a cookbook developer, I would like to be able use rewind method in my cookbook's custom resource so that I can rewind a library resource that I'm using inside my custom resource.

At the moment `rewind` is only usable in recipe. Using it inside `Resource` would raise `NoMethodError`.

**Comment by thommay** [comment]
I think this is absolutely not an approach I'd like to encourage. You should not rewind things in other resources, you should get that resource fixed to expose the API you need.
That said, in modern chef you can just use `edit_resource` in your resource.

**Comment by ceilfors** [comment]
Agree that the best approach is to fix the real issue, this is just a temporary workaround until the fix is implemented. I also can see that `edit_resource` is available in resource scope, thanks for this. Should [this](https://coderanger.net/rewind/) be documented in chef-rewind readme?
